/** Shared, deterministic customer estimate markup used by email and admin preview. */
export type EstimateEmailInput = { id: string; name: string; estimate: unknown; deposit: unknown; balance: unknown; notes?: unknown; approveUrl?: string; paymentLink?: string | null };
const esc = (v: unknown) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;", "'":"&#39;"}[c] as string));
const money = (v: unknown) => { const n = Number(String(v ?? "").replace(/[$,]/g, "")); return `$${(Number.isFinite(n) ? n : 0).toFixed(2)}`; };
export function buildEstimateHtml(input: EstimateEmailInput): string {
 const approve = input.approveUrl ? `<p><a href="${esc(input.approveUrl)}" style="display:inline-block;background:#235b3a;color:#fff;padding:14px 22px;border-radius:6px;text-decoration:none">Approve Estimate</a></p>` : "";
 const pay = input.paymentLink ? `<p><a href="${esc(input.paymentLink)}" style="display:inline-block;background:#8b5e3c;color:#fff;padding:14px 22px;border-radius:6px;text-decoration:none">Pay Online</a></p>` : "";
 return `<div style="font-family:Arial;color:#222"><div style="background:#235b3a;color:#fff;padding:28px"><strong style="font-size:22px">Hill Country Stump Co.</strong><br/>Stump grinding across the Texas Hill Country</div><div style="padding:28px"><h1>Estimate for ${esc(input.name)}</h1><p style="color:#666;font-size:12px">Reference ${esc(input.id)}</p><table style="width:100%;max-width:500px;border-collapse:collapse"><tr><td>Estimate amount</td><td>${money(input.estimate)}</td></tr><tr><td>Deposit<br/>due</td><td>${money(input.deposit)}</td></tr><tr><td>Balance due</td><td>${money(input.balance)}</td></tr></table>${input.notes ? `<p><strong>Notes</strong><br/>${esc(input.notes)}</p>` : ""}${approve}${pay}<p>Questions? Reply to this email and we'll get right back to you.</p></div><footer style="color:#777;padding:20px">Hill Country Stump Co. · hello@hillcountrystumpco.com</footer></div>`;
}
export function buildEstimateText(input: EstimateEmailInput): string { return `Estimate for ${input.name}\nReference: ${input.id}\nEstimate amount: ${money(input.estimate)}\nDeposit due: ${money(input.deposit)}\nBalance due: ${money(input.balance)}${input.notes ? `\nNotes: ${input.notes}` : ""}${input.approveUrl ? `\nApprove Estimate: ${input.approveUrl}` : ""}${input.paymentLink ? `\nPay Online: ${input.paymentLink}` : ""}\nQuestions? Reply to this email and we'll get right back to you.`; }
