import { Link } from "@tanstack/react-router";
import { breadcrumbSchema, faqPageSchema } from "~/lib/seo";
import { SERVICE_MAP, type ServiceContent } from "~/lib/services";
import { PHONE_DISPLAY, PHONE_TEL, SITE_NAME } from "~/lib/site";

export function ServicePage({ service }: { service: ServiceContent }) {
 const crumbs = [{name:"Home",path:"/"},{name:"Services",path:"/services"},{name:service.title,path:`/services/${service.slug}`}];
 return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema(crumbs))}} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqPageSchema(service.faqs))}} />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Service",name:service.title,description:service.intro,provider:{"@type":"LocalBusiness",name:SITE_NAME},areaServed:{"@type":"Place",name:"Texas Hill Country"}})}} />
  <section className="relative isolate overflow-hidden bg-forest-950"><img src="/images/hero-960.webp" width="960" height="640" alt="Stump grinding equipment in the Texas Hill Country" className="absolute inset-0 -z-10 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-forest-950/95 via-forest-950/80 to-forest-900/40"/><div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-limestone-200">{SITE_NAME} · Texas Hill Country</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-bold text-white sm:text-5xl">{service.title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-limestone-100">{service.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/estimate" className="btn-secondary">Get Free Estimate</Link><a href={`tel:${PHONE_TEL}`} className="btn-outline-light">Call {PHONE_DISPLAY}</a></div></div></section>
  <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8"><p className="max-w-3xl text-lg leading-relaxed text-charcoal-500">{service.intro}</p><div className="mt-12 grid gap-8 md:grid-cols-3"><Info title="What's included" items={service.included}/><Info title="Who it's for" items={service.forWho}/><Info title="How it works" items={service.process}/></div></section>
  <section className="bg-limestone-200 py-14"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><h2 className="section-title">Cleanup and finish options</h2><p className="mt-4 max-w-3xl text-base leading-relaxed text-charcoal-500">{service.cleanup}</p></div></section>
  <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:px-8"><h2 className="section-title">Questions about {service.title.toLowerCase()}</h2><div className="mt-8 max-w-3xl space-y-4">{service.faqs.map(f=><details className="card" key={f.q}><summary className="cursor-pointer font-display text-lg font-bold text-forest-900">{f.q}</summary><p className="mt-3 text-sm leading-relaxed text-charcoal-500">{f.a}</p></details>)}</div><h2 className="section-title mt-16">Related services</h2><div className="mt-6 flex flex-wrap gap-3">{service.related.map(slug=><Link key={slug} to={`/services/${slug}`} className="rounded-full border border-forest-700/30 bg-white px-4 py-2 text-sm font-semibold text-forest-800">{SERVICE_MAP[slug].title}</Link>)}<Link to="/services" className="rounded-full border border-forest-700/30 bg-white px-4 py-2 text-sm font-semibold text-forest-800">All services</Link><Link to="/contact" className="rounded-full border border-forest-700/30 bg-white px-4 py-2 text-sm font-semibold text-forest-800">Contact us</Link></div></section>
  <section className="bg-forest-700 py-14 text-center"><h2 className="font-display text-3xl font-bold text-limestone-50">Ready to plan this work?</h2><p className="mx-auto mt-3 max-w-xl text-limestone-200">Send photos and details for a free, no-pressure estimate.</p><Link to="/estimate" className="btn-secondary mt-7 inline-flex">Get Free Estimate</Link></section>
 </>;
}
function Info({title,items}:{title:string;items:string[]}) { return <div className="card"><h2 className="font-display text-2xl font-bold text-forest-900">{title}</h2><ul className="mt-5 space-y-3">{items.map(i=><li className="flex gap-2 text-sm leading-relaxed text-charcoal-500" key={i}><span className="font-bold text-forest-700">✓</span>{i}</li>)}</ul></div> }
