import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { deleteLead, getLead, getLeadPhoto, getSession, updateLead, sendEstimate } from "~/lib/admin";
import { LEAD_STATUSES } from "~/lib/admin-meta";
import type { LeadDetail, LeadStatus, EquipmentItem, ServiceCharge, JobSchedule, Subcontractor } from "~/lib/admin-meta";
import { SITE_NAME } from "~/lib/site";
export const Route = createFileRoute("/admin/lead/$id")({ head: () => ({ meta: [{ title: `Lead Detail | ${SITE_NAME} Admin` }, { name: "robots", content: "noindex, nofollow" }] }), component: LeadDetailPage });
const groups: Array<[string, string[]]> = [["Contact", ["name", "contact_name", "company", "phone", "email", "customer_email", "customer_type", "lead_source", "utm"]],["Location", ["address", "city", "zip"]],["Job details", ["num_stumps", "diameter", "height", "species", "grind_depth", "gate_width", "access_width", "utilities", "fence", "cleanup", "preferred_date", "notes"]],["Contractor partnership", ["monthly_volume", "coverage_area", "insurance", "partnership"]]];
const label = (s: string) => s.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const n = (v: unknown) => Number(String(v ?? "").replace(/[$,]/g, "")) || 0;
const fmt = (v: unknown) => `$${n(v).toFixed(2)}`;
function LeadDetailPage() {
 const { id } = Route.useParams(); const [lead,setLead]=useState<LeadDetail|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [dirty,setDirty]=useState(false); const [photoUrls,setPhotoUrls]=useState<string[]>([]);
 useEffect(()=>{(async()=>{try{const s=await getSession();if(!s.authed)return window.location.replace("/admin/login");const r=await getLead({data:{id}});if(r instanceof Response)return setError("Lead not found.");setLead(r as LeadDetail)}catch{setError("Unable to load lead.")}})()},[id]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 useEffect(()=>{if(!lead)return;let alive=true;(async()=>{const urls:string[]=[];for(const p of lead.photos??[]){const r=await getLeadPhoto({data:{leadId:id,filename:p.split("/").pop()??""}});if(r instanceof Response&&r.ok)urls.push(URL.createObjectURL(await r.blob()))}if(alive)setPhotoUrls(urls)})();return()=>{alive=false}},[lead,id]);
 async function save(patch:Record<string,unknown>){if(!lead)return;setSaving(true);setError("");try{const r=await updateLead({data:{id,patch}});if(r instanceof Response)throw Error();setLead(r.lead as LeadDetail);setDirty(false)}catch(e){const x=e as any;setError(x?.message||"Couldn't save — please try again")}finally{setSaving(false)}}
 async function saveAll(){if(!lead)return; await save({status:lead.status,estimate:lead.estimate,deposit:lead.deposit,schedule:lead.schedule,subcontractor:lead.subcontractor,contractor_cost:lead.contractor_cost,equipment:lead.equipment,fuel:lead.fuel,disposal:lead.disposal,management_fee:lead.management_fee,notes:lead.notes,payment_processing_cost:lead.payment_processing_cost,other_internal_cost:lead.other_internal_cost})}
 async function estimate(){try{const r=await sendEstimate({data:{id}});if(r instanceof Response||!r.ok)throw Error((r as any).error||"Send failed");setLead(r.lead as LeadDetail)}catch(e){setError(e instanceof Error?e.message:"Unable to send estimate")}}
 if(error&&!lead)return <div className="mx-auto max-w-3xl px-4 py-10"><div className="card">{error}<br/><Link to="/admin" className="text-forest-700">← Dashboard</Link></div></div>;
 if(!lead)return <div className="mx-auto max-w-3xl px-4 py-10"><div className="card">Loading lead…</div></div>;
 const schedule=(lead.schedule??null) as JobSchedule|null; const sub=(lead.subcontractor??null) as Subcontractor|null; const equipment=(lead.equipment??[]) as EquipmentItem[]; const charges=(lead.service_charges??[]) as ServiceCharge[]; const chargesTotal=charges.reduce((a,x)=>a+n(x.amount),0), equipTotal=equipment.reduce((a,x)=>a+n(x.cost),0); const customerTotal=n(lead.estimate)+chargesTotal, costsTotal=n(lead.contractor_cost)+equipTotal, profit=customerTotal-costsTotal-n(lead.management_fee);
 const patchArray=(key:string,arr:unknown[])=>save({[key]:arr});
 return <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><Link to="/admin" className="text-sm text-forest-700 hover:underline">← Back to dashboard</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="font-display text-3xl font-bold text-forest-900">{String(lead.name||lead.contact_name||lead.company||"Lead")}</h1><p className="mt-1 text-sm text-charcoal-500">{lead.id} · {new Date(lead.created_at).toLocaleString()}</p></div><button onClick={async()=>{if(confirm("Delete this lead and its uploaded photos?")){await deleteLead({data:{id}});window.location.href="/admin"}}} className="btn-charcoal bg-red-800 px-4 py-2 text-sm">Delete lead</button></div>{error&&<div className="mt-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
 <div className="card mt-6"><div className="mb-4 flex flex-wrap justify-end gap-2"><button onClick={saveAll} disabled={saving||!dirty} className="btn-primary px-4 py-2 text-sm">{saving?"Saving…":dirty?"Save":"Saved"}</button><button onClick={estimate} disabled={saving||!String(lead.estimate??"").trim()||n(lead.deposit)>n(lead.estimate)} className="btn-secondary px-4 py-2 text-sm">Send Estimate</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="label">Pipeline status<select className="input mt-1" value={lead.status} disabled={saving} onChange={e=>{setLead({...lead,status:e.target.value as LeadStatus});setDirty(true)}}>{LEAD_STATUSES.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label className="label">Estimate<input className="input mt-1" inputMode="decimal" value={String(lead.estimate??"")} onChange={e=>{setLead({...lead,estimate:e.target.value});setDirty(true)}} /></label><label className="label">Deposit<input className="input mt-1" inputMode="decimal" value={String(lead.deposit??"")} onChange={e=>{setLead({...lead,deposit:e.target.value});setDirty(true)}} /><span className="mt-1 block text-xs text-charcoal-500">Blank deposit is $0.00.</span></label><label className="label">Balance<input readOnly className="input mt-1 bg-limestone-100" value={fmt(Math.max(0,n(lead.estimate)-n(lead.deposit)))} /><span className="mt-1 block text-xs text-charcoal-500">Calculated automatically from estimate minus deposit.</span></label></div>{n(lead.deposit)>n(lead.estimate)&&<p className="mt-3 text-sm text-red-700">Deposit cannot exceed the total estimate.</p>}{dirty&&<p className="mt-2 text-sm text-charcoal-500">Unsaved changes</p>}</div>
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Scheduling</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="label">Service date<input type="date" className="input mt-1" value={schedule?.service_date??""} onChange={e=>setLead({...lead,schedule:{...(schedule??{arrival_time:null,estimated_duration_hours:null}),service_date:e.target.value||null}})} onBlur={e=>save({schedule:{...(schedule??{}),service_date:e.target.value||null}})}/></label><label className="label">Arrival time<input type="time" className="input mt-1" value={schedule?.arrival_time??""} onChange={e=>setLead({...lead,schedule:{...(schedule??{}),arrival_time:e.target.value||null}})} onBlur={e=>save({schedule:{...(schedule??{}),arrival_time:e.target.value||null}})}/></label><label className="label">Estimated duration (hours)<input className="input mt-1" inputMode="decimal" value={schedule?.estimated_duration_hours??""} onChange={e=>setLead({...lead,schedule:{...(schedule??{}),estimated_duration_hours:e.target.value||null}})} onBlur={e=>save({schedule:{...(schedule??{}),estimated_duration_hours:e.target.value||null}})}/></label></div></section>
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Subcontractor & payout</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Name<input className="input mt-1" value={sub?.name??""} onChange={e=>setLead({...lead,subcontractor:{...(sub??{phone:"",email:"",payout_status:"unpaid",payout_paid_at:null}),name:e.target.value}})} onBlur={e=>save({subcontractor:{...(sub??{}),name:e.target.value}})}/></label><label className="label">Phone<input className="input mt-1" value={sub?.phone??""} onChange={e=>setLead({...lead,subcontractor:{...(sub??{}),phone:e.target.value}})} onBlur={e=>save({subcontractor:{...(sub??{}),phone:e.target.value}})}/></label><label className="label">Email<input className="input mt-1" value={sub?.email??""} onChange={e=>setLead({...lead,subcontractor:{...(sub??{}),email:e.target.value}})} onBlur={e=>save({subcontractor:{...(sub??{}),email:e.target.value}})}/></label><label className="label">Contractor cost<input className="input mt-1" inputMode="decimal" value={String(lead.contractor_cost??"")} onChange={e=>setLead({...lead,contractor_cost:e.target.value})} onBlur={e=>save({contractor_cost:e.target.value})}/></label><label className="label">Payout status<select className="input mt-1" value={sub?.payout_status??"unpaid"} onChange={e=>{const paid=e.target.value==="paid";save({subcontractor:{...(sub??{}),payout_status:paid?"paid":"unpaid",payout_paid_at:paid?(sub?.payout_paid_at??new Date().toISOString()):null}})}}><option value="unpaid">Unpaid</option><option value="paid">Paid</option></select></label></div>{sub?.payout_paid_at&&<p className="mt-3 text-sm text-charcoal-500">Payout paid at: {new Date(sub.payout_paid_at).toLocaleString()}</p>}</section>
 <LineItems title="Equipment" rows={equipment} nameKey="name" amountKey="cost" addLabel="Add equipment" onSave={arr=>patchArray("equipment",arr)} total={equipTotal}/><LineItems title="Additional service charges" rows={charges} nameKey="description" amountKey="amount" addLabel="Add charge" onSave={arr=>patchArray("service_charges",arr)} total={chargesTotal}/>
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Internal costs</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="label">Company management fee<input className="input mt-1" inputMode="decimal" value={String(lead.management_fee??"")} onChange={e=>setLead({...lead,management_fee:e.target.value})} onBlur={e=>save({management_fee:e.target.value})}/></label><label className="label">Fuel<input className="input mt-1" inputMode="decimal" value={String(lead.fuel??"")} onChange={e=>setLead({...lead,fuel:e.target.value})} onBlur={e=>save({fuel:e.target.value})}/></label><label className="label">Disposal<input className="input mt-1" inputMode="decimal" value={String(lead.disposal??"")} onChange={e=>setLead({...lead,disposal:e.target.value})} onBlur={e=>save({disposal:e.target.value})}/></label></div></section>
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Job financial summary (auto-calculated)</h2><p className="mt-1 text-sm text-charcoal-500">Customer pricing − subcontractor and equipment costs − company management fee.</p><div className="mt-5 grid gap-5 sm:grid-cols-3"><div className="rounded-lg bg-forest-50 p-4"><strong className="text-forest-900">Customer pricing</strong><p>Estimate: {fmt(lead.estimate)}</p><p>Additional charges: {fmt(chargesTotal)}</p><p className="mt-2 font-bold">Customer total: {fmt(customerTotal)}</p></div><div className="rounded-lg bg-earth-100 p-4"><strong className="text-earth-800">Subcontractor costs</strong><p>Contractor: {fmt(lead.contractor_cost)}</p><p>Equipment: {fmt(equipTotal)}</p><p className="mt-2 font-bold">Costs total: {fmt(costsTotal)}</p></div><div className="rounded-lg bg-limestone-100 p-4"><strong>Company management fee</strong><p className="mt-2">Fee: {fmt(lead.management_fee)}</p><p className="mt-2 font-bold text-forest-800">Profit: {fmt(profit)}</p></div></div></section>
 
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Email History</h2><div className="mt-3 space-y-2">{(Array.isArray(lead.email_history) ? lead.email_history : []).slice().reverse().map((e: any) => <div key={e.id} className="rounded border border-limestone-200 p-3 text-sm"><div className="flex justify-between"><strong>{e.subject}</strong><span className="rounded bg-forest-100 px-2 py-0.5">{["customer-confirmation", "estimate-sent"].includes(e.type) ? "Customer" : "Internal"}</span><span className="rounded bg-limestone-100 px-2 py-0.5">{e.status}</span></div><div className="mt-1 text-charcoal-500">{e.recipient} · {new Date(e.sentAt).toLocaleString()} · {e.messageId || "No message ID"}</div></div>)}</div></section>
 {groups.map(([title,keys])=><section key={title} className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">{title}</h2><dl className="mt-4 grid gap-x-6 gap-y-3 sm:grid-cols-2">{keys.map(k=><div key={k}><dt className="text-xs font-semibold uppercase tracking-wide text-charcoal-500">{label(k)}</dt>{k==="customer_email"?<input className="input mt-1" defaultValue={String(lead[k]??"")} onBlur={e=>save({customer_email:e.target.value})}/>:k==="notes"?<textarea className="input mt-1 min-h-24" defaultValue={String(lead[k]??"")} onBlur={e=>save({notes:e.target.value})}/>:<dd className="mt-1 whitespace-pre-wrap text-charcoal-800">{k==="utm"?["source","medium","campaign"].map(x=>`${x}: ${String((lead.utm as any)?.[x]??"—")}`).join(" · "):String(lead[k]??"—")}</dd>}</div>)}</dl></section>)}
 <section className="card mt-5"><h2 className="font-display text-xl font-bold text-forest-900">Uploaded photos</h2>{photoUrls.length?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{photoUrls.map(u=><img key={u} src={u} className="aspect-square rounded-lg object-cover" alt="Uploaded stump"/>)}</div>:<p className="mt-3 text-charcoal-500">No photos uploaded.</p>}</section></div>;
}
function LineItems({title,rows,nameKey,amountKey,addLabel,onSave,total}:{title:string;rows:Array<any>;nameKey:string;amountKey:string;addLabel:string;onSave:(r:any[])=>void;total:number}) { const [items,setItems]=useState(rows); useEffect(()=>setItems(rows),[rows.length]); const update=(i:number,k:string,v:string)=>setItems(items.map((x,j)=>j===i?{...x,[k]:v}:x)); return <section className="card mt-5"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-forest-900">{title}</h2><button className="btn-secondary px-3 py-1.5 text-sm" onClick={()=>setItems([...items,{id:crypto.randomUUID(),[nameKey]:"",[amountKey]:""}])}>+ {addLabel}</button></div><div className="mt-4 space-y-3">{items.map((x,i)=><div className="flex gap-2" key={x.id}><input className="input" placeholder={nameKey==="name"?"Equipment name":"Description"} value={x[nameKey]} onChange={e=>update(i,nameKey,e.target.value)} onBlur={()=>onSave(items)}/><input className="input max-w-40" placeholder="Cost" inputMode="decimal" value={x[amountKey]} onChange={e=>update(i,amountKey,e.target.value)} onBlur={()=>onSave(items)}/><button className="text-sm text-red-700" onClick={()=>{const next=items.filter((_,j)=>j!==i);setItems(next);onSave(next)}}>Remove</button></div>)}</div><p className="mt-3 text-right text-sm font-semibold">Total: {fmt(total)}</p></section>;
}
